package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
)

var (
	JSON = `{
		"id": 11,
		"title": "perfume Oil",
		"description": "Mega Discount, Impression of A...",
		"price": 13,
		"discountPercentage": 8.4,
		"rating": 4.26,
		"stock": 65,
		"brand": "Impression of Acqua Di Gio",
		"category": "fragrances",
		"thumbnail": "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
		"images": [
		  "https://i.dummyjson.com/data/products/11/1.jpg",
		  "https://i.dummyjson.com/data/products/11/2.jpg",
		  "https://i.dummyjson.com/data/products/11/3.jpg",
		  "https://i.dummyjson.com/data/products/11/thumbnail.jpg"
		]
	  }`
)

type AutoGenerated struct {
	ID                 int      `json:"id"`
	Title              string   `json:"title"`
	Description        string   `json:"description"`
	Price              int      `json:"price"`
	DiscountPercentage float64  `json:"discountPercentage"`
	Rating             float64  `json:"rating"`
	Stock              int      `json:"stock"`
	Brand              string   `json:"brand"`
	Category           string   `json:"category"`
	Thumbnail          string   `json:"thumbnail"`
	Images             []string `json:"images"`
}

func main() {
	var ag AutoGenerated

	err := json.Unmarshal([]byte(JSON), &ag)
	if err != nil {
		fmt.Println("Cannot unmarshal from json to struct")
		return
	}

	fmt.Printf("The struct is: %+v\n", ag)

	ag.ID = 15

	bx, err := json.Marshal(ag)
	if err != nil {
		fmt.Println("Cannot marshal to Json from struct")
		return
	}

	err = ioutil.WriteFile("product.json", bx, 777)
	if err != nil {
		fmt.Println("cannot create and write json to product.json file")
	}
}
